#!/bin/bash
#immfind sorted_dns
mkdir imm_snapshot > /dev/null
\rm imm_snapshot/*
immfind | sed  's:\\:\\\\:g' > immfind_dump
( xargs -I {} -i bash -c 'immlist "{}" | grep -v SaImmAttrAdminOwnerName | sort -u > "imm_snapshot/dn_`echo "{}" | md5sum | cut -d " " -f1`"' ) < immfind_dump 
