#!/usr/bin/expect

#################################################################################################################
#                                                                                                               #
# Please check the path of expect (in the first line of this file)!                                             #
#                                                                                                               #
# Description:                                                                                                  #
#                                                                                                               #
#    Log in as root:rootroot and set password for a new user. Unique case.                                      #
#                                                                                                               #
# Usage:                                                                                                        #
#                                                                                                               #
#    You must add 3 arguments for the script.                                                                   #
#																		                                        #
#                                                                                                               #
#   ./SetUserPassword <target ipaddress> <new_user> <new_password>     											#
#                                                                                                               #
# Example:                                                                                                      #
#                                                                                                               #
#   ./SetUserPassword 134.138.66.123 test testtest   	 									   			        #
#                                                                                                               #
#################################################################################################################

set ip [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]


set target_ip_address [lindex [split $ip ":"] 0]
set port [lindex [split $ip ":"] 1 ]

if { "" == $port } {
    spawn ssh root@$target_ip_address
} else {
    spawn ssh root@$target_ip_address -p $port
}

expect "*assword:*"

send -- "rootroot\r"
expect "SC-2-*"

send -- "passwd $username\r"
expect "*New password:"

send -- "$password\r"
expect "*Retype new password:"

send -- "$password\r"
expect "*all authentication tokens updated successfully"

send -- "exit\n"
expect "*>>"
